//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlGuyTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlGuyTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;bookstore &gt;&lt;locations &gt;&lt;location store_id=&quot;1&quot; address=&quot;21 Jump St&quot; phone=&quot;123456&quot;  /&gt;&lt;location store_id=&quot;2&quot; address=&quot;342 Pitt St&quot; phone=&quot;9876543&quot;  /&gt;&lt;/locations&gt;&lt;books &gt;&lt;book title=&quot;The Enchiridion&quot; price=&quot;9.75&quot; &gt;&lt;author &gt;Epictetus&lt;/author&gt;&lt;stores_with_stock &gt;&lt;store store_id=&quot;1&quot;  /&gt;&lt;/stores_with_stock&gt;&lt;/book&gt;&lt;book title=&quot;Signal to Noise&quot; price=&quot;5.82&quot; &gt;&lt;author &gt;Neil Gaiman&lt;/author&gt;&lt;author &gt;Dave McKean&lt;/author&gt;&lt;stores_with_stock &gt;&lt;store store_id=&quot;1&quot;  /&gt;&lt;store store_id=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookstoreExpectedNotPretty {
            get {
                return ResourceManager.GetString("BookstoreExpectedNotPretty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;bookstore &gt;
        ///	&lt;locations &gt;
        ///		&lt;location store_id=&quot;1&quot; address=&quot;21 Jump St&quot; phone=&quot;123456&quot;  /&gt;
        ///		&lt;location store_id=&quot;2&quot; address=&quot;342 Pitt St&quot; phone=&quot;9876543&quot;  /&gt;
        ///	&lt;/locations&gt;
        ///	&lt;books &gt;
        ///		&lt;book title=&quot;The Enchiridion&quot; price=&quot;9.75&quot; &gt;
        ///			&lt;author &gt;Epictetus&lt;/author&gt;
        ///			&lt;stores_with_stock &gt;
        ///				&lt;store store_id=&quot;1&quot;  /&gt;
        ///			&lt;/stores_with_stock&gt;
        ///		&lt;/book&gt;
        ///		&lt;book title=&quot;Signal to Noise&quot; price=&quot;5.82&quot; &gt;
        ///			&lt;author &gt;Neil Gaiman&lt;/author&gt;
        ///			&lt;author &gt;Dave McKean&lt;/author [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookstoreExpectedPretty {
            get {
                return ResourceManager.GetString("BookstoreExpectedPretty", resourceCulture);
            }
        }
    }
}
